# Generated by Django 5.1.15 on 2026-09-08 23:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drugs', '0002_atccategory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeitnerCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box', models.PositiveSmallIntegerField(default=1)),
                ('due_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('times_seen', models.PositiveIntegerField(default=0)),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leitner_cards', to='drugs.ingredient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leitner_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['due_at', 'id'],
                'indexes': [models.Index(fields=['user', 'due_at'], name='flashcards_user_due_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'ingredient'), name='flashcards_unique_user_ingredient')],
            },
        ),
    ]
