# Generated by Django 5.1.15 on 2026-07-04 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


PRODUCT_ID = "pharmexa"


def drug_learning_object_external_id(drug):
    return drug.external_id or f"drug:{drug.id}"


def drug_question_source_external_id(source_id):
    return f"drug-question-source:{source_id}"


def sync_knowledge_source(apps, source):
    LearningTopic = apps.get_model("learning", "LearningTopic")
    LearningObject = apps.get_model("learning", "LearningObject")
    KnowledgeSource = apps.get_model("learning", "KnowledgeSource")

    topic, _ = LearningTopic.objects.update_or_create(
        product_id=PRODUCT_ID,
        key=source.topic.key,
        defaults={
            "label": source.topic.label,
            "detail": source.topic.detail,
            "metadata": {
                "legacy_model": "drugs.DrugTopic",
                "legacy_id": source.topic_id,
            },
            "is_active": True,
        },
    )

    drug = source.drug
    display_name = (
        drug.brand_name
        or drug.name
        or drug.persian_name
        or drug.external_id
    )
    learning_object, _ = LearningObject.objects.update_or_create(
        product_id=PRODUCT_ID,
        external_id=drug_learning_object_external_id(drug),
        defaults={
            "display_name": display_name,
            "subtitle": drug.generic_name or drug.drug_classification,
            "topic": topic,
            "metadata": {
                "legacy_model": "drugs.Drug",
                "legacy_id": drug.id,
                "source_file": drug.source_file,
                "domain": "pharmacology",
            },
            "is_active": True,
        },
    )

    knowledge_source, _ = KnowledgeSource.objects.update_or_create(
        product_id=PRODUCT_ID,
        external_id=drug_question_source_external_id(source.id),
        defaults={
            "learning_object": learning_object,
            "topic": topic,
            "source_type": source.question_type,
            "prompt": source.prompt,
            "correct_answer": source.correct_answer,
            "explanation": source.feedback,
            "metadata": {
                "legacy_model": "drugs.DrugQuestionSource",
                "legacy_id": source.id,
                "subtitle": source.subtitle,
                "chip": source.chip,
            },
            "is_active": source.is_active,
        },
    )
    return knowledge_source


def populate_flashcard_knowledge_sources(apps, schema_editor):
    FlashcardState = apps.get_model("flashcards", "FlashcardState")

    for state in FlashcardState.objects.select_related("source__drug", "source__topic").filter(source__isnull=False):
        state.knowledge_source = sync_knowledge_source(apps, state.source)
        state.save(update_fields=["knowledge_source"])


def clear_flashcard_knowledge_sources(apps, schema_editor):
    FlashcardState = apps.get_model("flashcards", "FlashcardState")
    FlashcardState.objects.update(knowledge_source=None)


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0001_initial'),
        ('flashcards', '0001_initial'),
        ('learning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcardstate',
            name='knowledge_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flashcard_states', to='learning.knowledgesource'),
        ),
        migrations.AlterField(
            model_name='flashcardstate',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drugs.drugquestionsource'),
        ),
        migrations.RunPython(populate_flashcard_knowledge_sources, clear_flashcard_knowledge_sources),
        migrations.AddConstraint(
            model_name='flashcardstate',
            constraint=models.UniqueConstraint(fields=('user', 'knowledge_source'), name='unique_user_knowledge_flashcard'),
        ),
    ]
