# Generated by Django 5.1.15 on 2026-07-04 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0002_align_with_knowledge_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcardreview',
            name='box_after',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='flashcardreview',
            name='box_before',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='flashcardreview',
            name='interval_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flashcardreview',
            name='rule_version',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='flashcardreview',
            name='scheduled_due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flashcardstate',
            name='interval_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flashcardstate',
            name='lapse_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flashcardstate',
            name='last_rating',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='flashcardstate',
            name='review_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flashcardstate',
            name='review_state',
            field=models.CharField(choices=[('new', 'New'), ('learning', 'Learning'), ('review', 'Review'), ('mature', 'Mature'), ('suspended', 'Suspended')], default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='flashcardstate',
            name='schedule_rule_version',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
