# Generated by Django 5.1.15 on 2026-07-03 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('persian_name', models.CharField(blank=True, max_length=255)),
                ('brand_name', models.TextField(blank=True)),
                ('generic_name', models.TextField(blank=True)),
                ('dosage_form', models.TextField(blank=True)),
                ('drug_classification', models.TextField(blank=True)),
                ('consumption_time', models.TextField(blank=True)),
                ('consumption_time_sorted', models.CharField(blank=True, max_length=80)),
                ('indication', models.TextField(blank=True)),
                ('indication_answer', models.TextField(blank=True)),
                ('side_effects', models.TextField(blank=True)),
                ('side_effects_answer', models.TextField(blank=True)),
                ('source_topic', models.CharField(blank=True, max_length=255)),
                ('source_file', models.CharField(blank=True, max_length=255)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DrugTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=120)),
                ('detail', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DrugQuestionSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('timing', 'با غذا / بی غذا'), ('brandGeneric', 'نام تجاری / ژنریک'), ('indication', 'اندیکاسیون'), ('sideEffects', 'عوارض جانبی')], max_length=50)),
                ('prompt', models.TextField()),
                ('subtitle', models.TextField(blank=True)),
                ('chip', models.TextField(blank=True)),
                ('correct_answer', models.TextField()),
                ('feedback', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_sources', to='drugs.drug')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_sources', to='drugs.drugtopic')),
            ],
            options={
                'indexes': [models.Index(fields=['question_type', 'is_active'], name='drugs_drugq_questio_cda341_idx')],
                'unique_together': {('topic', 'drug', 'question_type', 'correct_answer')},
            },
        ),
    ]
