# Generated by Django 5.1.15 on 2026-09-08 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AtcCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rxcui', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(max_length=280, unique=True)),
                ('n_products', models.PositiveIntegerField(default=0, help_text='Distinct products contributing to this ingredient profile.')),
                ('n_source_records', models.PositiveIntegerField(default=0, help_text='Source label records rolled up into this profile.')),
                ('pharm_classes', models.JSONField(blank=True, default=list)),
                ('source_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('atc_codes', models.ManyToManyField(blank=True, related_name='ingredients', to='drugs.atccode')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IngredientProfileSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(choices=[('indications_and_usage', 'Indications and usage'), ('dosage_and_administration', 'Dosage and administration'), ('dosage_forms_and_strengths', 'Dosage forms and strengths'), ('contraindications', 'Contraindications'), ('do_not_use', 'Do not use'), ('boxed_warning', 'Boxed warning'), ('warnings', 'Warnings'), ('adverse_reactions', 'Adverse reactions'), ('drug_interactions', 'Drug interactions'), ('pregnancy', 'Pregnancy'), ('abuse', 'Abuse'), ('clinical_pharmacology', 'Clinical pharmacology')], max_length=40)),
                ('raw_text', models.TextField(blank=True)),
                ('n_contributing_products', models.PositiveIntegerField(default=0)),
                ('summary_fa', models.TextField(blank=True)),
                ('summary_en', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='drugs.ingredient')),
            ],
            options={
                'ordering': ['ingredient', 'field'],
                'indexes': [models.Index(fields=['field'], name='drugs_section_field_idx')],
                'constraints': [models.UniqueConstraint(fields=('ingredient', 'field'), name='drugs_unique_ingredient_field')],
            },
        ),
    ]
