# Generated by Django 5.1.15 on 2026-07-11 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='atc_categories',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='drug',
            name='atc_classes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='drug',
            name='atc_codes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='drug',
            name='atc_subclasses',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='drug',
            name='breastfeeding',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='drug',
            name='clinical_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='drug',
            name='dose_adjustment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='drug',
            name='dosing_and_administration',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='drug',
            name='extra_attributes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='drug',
            name='pregnancy',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='drug',
            name='source_row',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='drug',
            name='source_table',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='drugquestionsource',
            name='question_type',
            field=models.CharField(choices=[('timing', 'با غذا / بی غذا'), ('brandGeneric', 'نام تجاری / ژنریک'), ('indication', 'اندیکاسیون'), ('sideEffects', 'عوارض جانبی'), ('classification', 'دسته\u200cبندی'), ('dosageForm', 'اشکال دارویی'), ('dosing', 'دوزینگ و دستور مصرف'), ('pregnancy', 'بارداری و شیردهی'), ('doseAdjustment', 'تنظیم دوز')], max_length=50),
        ),
        migrations.CreateModel(
            name='DrugDatasetDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_version', models.CharField(max_length=20)),
                ('source_file', models.CharField(max_length=255)),
                ('source_path', models.TextField(blank=True)),
                ('source_format', models.CharField(blank=True, max_length=40)),
                ('source_size_bytes', models.PositiveBigIntegerField(default=0)),
                ('source_sha256', models.CharField(max_length=64, unique=True)),
                ('source_metadata', models.JSONField(blank=True, default=dict)),
                ('extraction_metadata', models.JSONField(blank=True, default=dict)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('enrichment_metadata', models.JSONField(blank=True, default=dict)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['source_file'], name='drugs_drugd_source__ed3c5b_idx'), models.Index(fields=['schema_version'], name='drugs_drugd_schema__e141f9_idx')],
            },
        ),
        migrations.AddField(
            model_name='drug',
            name='dataset_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drugs', to='drugs.drugdatasetdocument'),
        ),
        migrations.AddIndex(
            model_name='drug',
            index=models.Index(fields=['source_file', 'source_table', 'source_row'], name='drugs_drug_source__2a0f29_idx'),
        ),
    ]
