# Generated by Django 5.1.15 on 2026-09-08 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtcCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('name_en', models.CharField(max_length=200)),
                ('name_fa', models.CharField(max_length=200)),
                ('level', models.PositiveSmallIntegerField()),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='drugs.atccategory')),
            ],
            options={
                'verbose_name_plural': 'ATC categories',
                'ordering': ['code'],
            },
        ),
    ]
