# Generated by Django 5.1.15 on 2026-07-12 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0002_drug_atc_categories_drug_atc_classes_drug_atc_codes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='consumption_time_sorted',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
