# Generated by Django 5.1.15 on 2026-07-12 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0003_alter_drug_consumption_time_sorted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='consumption_time_sorted',
            field=models.TextField(blank=True),
        ),
    ]
