# Generated by Django 5.1.15 on 2026-07-04 19:45

from datetime import timedelta
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def week_bounds(value):
    current = timezone.localtime(value)
    starts_at = (current - timedelta(days=current.weekday())).replace(
        hour=0,
        minute=0,
        second=0,
        microsecond=0,
    )
    return starts_at, starts_at + timedelta(days=7)


def season_key_for(starts_at):
    year, week, _ = starts_at.isocalendar()
    return f"{year}-W{week:02d}"


def backfill_league_seasons(apps, schema_editor):
    LeagueResult = apps.get_model("league", "LeagueResult")
    LeagueSeason = apps.get_model("league", "LeagueSeason")

    for result in LeagueResult.objects.filter(season__isnull=True):
        product_id = result.product_id or "k_game"
        starts_at, ends_at = week_bounds(result.created_at)
        key = season_key_for(starts_at)
        season, _ = LeagueSeason.objects.get_or_create(
            product_id=product_id,
            key=key,
            defaults={
                "starts_at": starts_at,
                "ends_at": ends_at,
                "status": "active",
            },
        )
        result.product_id = product_id
        result.season = season
        result.season_key = key
        result.league_rule_version = result.league_rule_version or "mvp-weekly-league-v1"
        result.save(update_fields=["product_id", "season", "season_key", "league_rule_version"])


def clear_league_seasons(apps, schema_editor):
    LeagueResult = apps.get_model("league", "LeagueResult")
    LeagueResult.objects.update(season=None, season_key="")


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_stabilize_assessment_state'),
        ('league', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leagueresult',
            options={'ordering': ['-league_rating', '-raw_score', '-percent', '-time_remaining_total', 'created_at']},
        ),
        migrations.AddField(
            model_name='leagueresult',
            name='league_rule_version',
            field=models.CharField(default='mvp-weekly-league-v1', max_length=80),
        ),
        migrations.AddField(
            model_name='leagueresult',
            name='product_id',
            field=models.CharField(default='k_game', max_length=80),
        ),
        migrations.AddField(
            model_name='leagueresult',
            name='rank_snapshot',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leagueresult',
            name='season_key',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.CreateModel(
            name='LeagueSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(default='k_game', max_length=80)),
                ('key', models.CharField(max_length=40)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-starts_at'],
                'indexes': [models.Index(fields=['product_id', 'key'], name='league_leag_product_d88804_idx'), models.Index(fields=['product_id', 'status'], name='league_leag_product_432733_idx'), models.Index(fields=['starts_at', 'ends_at'], name='league_leag_starts__ae4998_idx')],
                'constraints': [models.UniqueConstraint(fields=('product_id', 'key'), name='unique_product_league_season')],
            },
        ),
        migrations.AddField(
            model_name='leagueresult',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='league.leagueseason'),
        ),
        migrations.RunPython(backfill_league_seasons, clear_league_seasons),
        migrations.AddIndex(
            model_name='leagueresult',
            index=models.Index(fields=['product_id', 'season_key', 'topic_key'], name='league_leag_product_53934a_idx'),
        ),
        migrations.AddIndex(
            model_name='leagueresult',
            index=models.Index(fields=['user', 'created_at'], name='league_leag_user_id_e450d9_idx'),
        ),
    ]
