# Generated by Django 5.1.15 on 2026-09-12 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyplan',
            name='daily_minutes',
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='studyplan',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studyplan',
            name='mode',
            field=models.CharField(choices=[('none', 'Free study'), ('goal', 'Goal-based path'), ('maintenance', 'Ongoing review')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='studyplan',
            name='topic_keys',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='StudyPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('activity_type', models.CharField(choices=[('lesson', 'Lesson'), ('quiz', 'Quiz'), ('flashcards', 'Flashcards'), ('mistake_review', 'Mistake review')], max_length=20)),
                ('topic_key', models.CharField(blank=True, max_length=60)),
                ('atc_code', models.CharField(blank=True, max_length=3)),
                ('estimated_minutes', models.PositiveSmallIntegerField(default=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('skipped', 'Skipped')], default='pending', max_length=10)),
                ('reason_fa', models.CharField(blank=True, max_length=200)),
                ('reason_en', models.CharField(blank=True, max_length=200)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='progress.studyplan')),
            ],
            options={
                'ordering': ['day', 'order'],
            },
        ),
    ]
