# Generated by Django 5.1.15 on 2026-07-04 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnerProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=80)),
                ('questions_answered', models.PositiveIntegerField(default=0)),
                ('correct_answers', models.PositiveIntegerField(default=0)),
                ('wrong_answers', models.PositiveIntegerField(default=0)),
                ('timed_out_answers', models.PositiveIntegerField(default=0)),
                ('xp', models.IntegerField(default=0)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('mistake_count', models.PositiveIntegerField(default=0)),
                ('mastery_state', models.CharField(choices=[('unseen', 'Unseen'), ('seen', 'Seen'), ('practicing', 'Practicing'), ('reviewing', 'Reviewing'), ('mastered', 'Mastered')], default='unseen', max_length=20)),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_progress', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learner_progress', to='learning.learningtopic')),
            ],
            options={
                'indexes': [models.Index(fields=['learner', 'product_id'], name='learning_le_learner_b3a599_idx'), models.Index(fields=['learner', 'mastery_state'], name='learning_le_learner_0e0c58_idx'), models.Index(fields=['product_id', 'topic'], name='learning_le_product_b7c1e9_idx')],
                'constraints': [models.UniqueConstraint(fields=('learner', 'product_id', 'topic'), name='unique_learner_product_topic_progress')],
            },
        ),
    ]
