# Generated by Django 5.1.15 on 2026-07-12 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_rename_legacy_product_to_pharmexa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningobject',
            name='display_name',
            field=models.TextField(),
        ),
    ]
