# Generated by Django 5.1.15 on 2026-07-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0004_alter_learningobject_display_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="knowledgesource",
            name="external_id",
            field=models.CharField(max_length=255),
        ),
    ]
