# Generated by Django 5.1.15 on 2026-10-02 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('disease', 'Disease'), ('guideline', 'Guideline')], max_length=16)),
                ('source_id', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=320, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('meta', models.TextField(blank=True)),
                ('url', models.URLField(blank=True, max_length=600)),
                ('categories', models.JSONField(default=list)),
                ('sections', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title'],
                'indexes': [models.Index(fields=['kind'], name='medscape_ar_kind_c379a4_idx')],
            },
        ),
    ]
