# Generated by Django 5.1.15 on 2026-10-07 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medscape', '0002_articleimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='latest_update',
            field=models.DateField(blank=True, null=True),
        ),
    ]
