import React from "react";
import { Image, ImageStyle, StyleProp } from "react-native";

// Static registry — Metro needs literal require() paths.
export const ICONS = {
  "app-logo": require("../../../assets/icons/app-logo.png"),
  "cat-cardio-blood": require("../../../assets/icons/cat-cardio-blood.png"),
  "cat-dermatology": require("../../../assets/icons/cat-dermatology.png"),
  "cat-endocrine-metabolic": require("../../../assets/icons/cat-endocrine-metabolic.png"),
  "cat-gi": require("../../../assets/icons/cat-gi.png"),
  "cat-infection": require("../../../assets/icons/cat-infection.png"),
  "cat-misc": require("../../../assets/icons/cat-misc.png"),
  "cat-musculoskeletal": require("../../../assets/icons/cat-musculoskeletal.png"),
  "cat-neuro-psych": require("../../../assets/icons/cat-neuro-psych.png"),
  "cat-onco-immune": require("../../../assets/icons/cat-onco-immune.png"),
  "cat-renal-gu": require("../../../assets/icons/cat-renal-gu.png"),
  "cat-respiratory": require("../../../assets/icons/cat-respiratory.png"),
  "cat-sensory": require("../../../assets/icons/cat-sensory.png"),
  "edu-flashcards": require("../../../assets/icons/edu-flashcards.png"),
  "edu-lessons": require("../../../assets/icons/edu-lessons.png"),
  "edu-mistakes": require("../../../assets/icons/edu-mistakes.png"),
  "edu-profile": require("../../../assets/icons/edu-profile.png"),
  "edu-quiz": require("../../../assets/icons/edu-quiz.png"),
  "edu-stats": require("../../../assets/icons/edu-stats.png"),
  "empty-state": require("../../../assets/icons/empty-state.png"),
  "entry-calculator": require("../../../assets/icons/entry-calculator.png"),
  "entry-diseases": require("../../../assets/icons/entry-diseases.png"),
  "entry-education": require("../../../assets/icons/entry-education.png"),
  "entry-guidelines": require("../../../assets/icons/entry-guidelines.png"),
  "entry-next-chapter": require("../../../assets/icons/entry-next-chapter.png"),
  "entry-today-plan": require("../../../assets/icons/entry-today-plan.png"),
  "lexicomp-logo": require("../../../assets/icons/lexicomp-logo.png"),
  "med-medicine": require("../../../assets/icons/med-medicine.png"),
  "nav-flashcards": require("../../../assets/icons/nav-flashcards.png"),
  "nav-home": require("../../../assets/icons/nav-home.png"),
  "nav-lessons": require("../../../assets/icons/nav-lessons.png"),
  "nav-profile": require("../../../assets/icons/nav-profile.png"),
  "nav-quiz": require("../../../assets/icons/nav-quiz.png"),
  "offline": require("../../../assets/icons/offline.png"),
  "profile-full-stats": require("../../../assets/icons/profile-full-stats.png"),
  "profile-logout": require("../../../assets/icons/profile-logout.png"),
  "profile-notifications": require("../../../assets/icons/profile-notifications.png"),
  "profile-planning": require("../../../assets/icons/profile-planning.png"),
  "spec-admin": require("../../../assets/icons/spec-admin.png"),
  "spec-cardiology": require("../../../assets/icons/spec-cardiology.png"),
  "spec-covid": require("../../../assets/icons/spec-covid.png"),
  "spec-critical-care": require("../../../assets/icons/spec-critical-care.png"),
  "spec-emergency": require("../../../assets/icons/spec-emergency.png"),
  "spec-endocrinology": require("../../../assets/icons/spec-endocrinology.png"),
  "spec-ent": require("../../../assets/icons/spec-ent.png"),
  "spec-gastro": require("../../../assets/icons/spec-gastro.png"),
  "spec-general": require("../../../assets/icons/spec-general.png"),
  "spec-geriatrics": require("../../../assets/icons/spec-geriatrics.png"),
  "spec-hematology": require("../../../assets/icons/spec-hematology.png"),
  "spec-imaging": require("../../../assets/icons/spec-imaging.png"),
  "spec-infectious": require("../../../assets/icons/spec-infectious.png"),
  "spec-mental-health": require("../../../assets/icons/spec-mental-health.png"),
  "spec-nephrology": require("../../../assets/icons/spec-nephrology.png"),
  "spec-neurology": require("../../../assets/icons/spec-neurology.png"),
  "spec-obgyn": require("../../../assets/icons/spec-obgyn.png"),
  "spec-oncology": require("../../../assets/icons/spec-oncology.png"),
  "spec-orthopedics": require("../../../assets/icons/spec-orthopedics.png"),
  "spec-pathology": require("../../../assets/icons/spec-pathology.png"),
  "spec-pediatrics": require("../../../assets/icons/spec-pediatrics.png"),
  "spec-physio": require("../../../assets/icons/spec-physio.png"),
  "spec-preventive": require("../../../assets/icons/spec-preventive.png"),
  "spec-rehab": require("../../../assets/icons/spec-rehab.png"),
  "spec-respirology": require("../../../assets/icons/spec-respirology.png"),
  "spec-rheumatology": require("../../../assets/icons/spec-rheumatology.png"),
  "spec-surgery": require("../../../assets/icons/spec-surgery.png"),
  "spec-transplant": require("../../../assets/icons/spec-transplant.png"),
  "spec-urology": require("../../../assets/icons/spec-urology.png"),
  "spec-vascular": require("../../../assets/icons/spec-vascular.png"),
  "stat-accuracy": require("../../../assets/icons/stat-accuracy.png"),
  "stat-mastery": require("../../../assets/icons/stat-mastery.png"),
  "stat-quizzes": require("../../../assets/icons/stat-quizzes.png"),
  "stat-streak": require("../../../assets/icons/stat-streak.png"),
  "stat-xp": require("../../../assets/icons/stat-xp.png"),
  "topic-cns-anesthesia": require("../../../assets/icons/topic-cns-anesthesia.png"),
  "topic-cns-depression": require("../../../assets/icons/topic-cns-depression.png"),
  "topic-cns-epilepsy": require("../../../assets/icons/topic-cns-epilepsy.png"),
  "topic-cns-other": require("../../../assets/icons/topic-cns-other.png"),
  "topic-cns-pain": require("../../../assets/icons/topic-cns-pain.png"),
  "topic-cns-parkinson": require("../../../assets/icons/topic-cns-parkinson.png"),
  "topic-cns-psychosis": require("../../../assets/icons/topic-cns-psychosis.png"),
  "topic-cv-angina": require("../../../assets/icons/topic-cv-angina.png"),
  "topic-cv-arrhythmia": require("../../../assets/icons/topic-cv-arrhythmia.png"),
  "topic-cv-hf": require("../../../assets/icons/topic-cv-hf.png"),
  "topic-cv-htn": require("../../../assets/icons/topic-cv-htn.png"),
  "topic-cv-lipid": require("../../../assets/icons/topic-cv-lipid.png"),
  "topic-cv-peripheral": require("../../../assets/icons/topic-cv-peripheral.png"),
  "topic-dental": require("../../../assets/icons/topic-dental.png"),
  "topic-derm-acne": require("../../../assets/icons/topic-derm-acne.png"),
  "topic-derm-cortico": require("../../../assets/icons/topic-derm-cortico.png"),
  "topic-derm-infection": require("../../../assets/icons/topic-derm-infection.png"),
  "topic-derm-other": require("../../../assets/icons/topic-derm-other.png"),
  "topic-derm-wound": require("../../../assets/icons/topic-derm-wound.png"),
  "topic-endo-cortico": require("../../../assets/icons/topic-endo-cortico.png"),
  "topic-endo-diabetes": require("../../../assets/icons/topic-endo-diabetes.png"),
  "topic-endo-obesity": require("../../../assets/icons/topic-endo-obesity.png"),
  "topic-endo-pituitary": require("../../../assets/icons/topic-endo-pituitary.png"),
  "topic-endo-sex": require("../../../assets/icons/topic-endo-sex.png"),
  "topic-endo-thyroid": require("../../../assets/icons/topic-endo-thyroid.png"),
  "topic-gi-bowel": require("../../../assets/icons/topic-gi-bowel.png"),
  "topic-gi-liver": require("../../../assets/icons/topic-gi-liver.png"),
  "topic-gi-nausea": require("../../../assets/icons/topic-gi-nausea.png"),
  "topic-gi-upper": require("../../../assets/icons/topic-gi-upper.png"),
  "topic-gu-infection": require("../../../assets/icons/topic-gu-infection.png"),
  "topic-gu-tract": require("../../../assets/icons/topic-gu-tract.png"),
  "topic-heme-clot": require("../../../assets/icons/topic-heme-clot.png"),
  "topic-heme-other": require("../../../assets/icons/topic-heme-other.png"),
  "topic-immune-mod": require("../../../assets/icons/topic-immune-mod.png"),
  "topic-infect-bacteria": require("../../../assets/icons/topic-infect-bacteria.png"),
  "topic-infect-fungus": require("../../../assets/icons/topic-infect-fungus.png"),
  "topic-infect-immuno": require("../../../assets/icons/topic-infect-immuno.png"),
  "topic-infect-tb": require("../../../assets/icons/topic-infect-tb.png"),
  "topic-infect-virus": require("../../../assets/icons/topic-infect-virus.png"),
  "topic-misc-other": require("../../../assets/icons/topic-misc-other.png"),
  "topic-msk-bone": require("../../../assets/icons/topic-msk-bone.png"),
  "topic-msk-gout": require("../../../assets/icons/topic-msk-gout.png"),
  "topic-msk-nsaid": require("../../../assets/icons/topic-msk-nsaid.png"),
  "topic-msk-relaxant": require("../../../assets/icons/topic-msk-relaxant.png"),
  "topic-onco-chemo": require("../../../assets/icons/topic-onco-chemo.png"),
  "topic-parasite": require("../../../assets/icons/topic-parasite.png"),
  "topic-resp-allergy": require("../../../assets/icons/topic-resp-allergy.png"),
  "topic-resp-coldcough": require("../../../assets/icons/topic-resp-coldcough.png"),
  "topic-resp-obstructive": require("../../../assets/icons/topic-resp-obstructive.png"),
  "topic-sense-ear": require("../../../assets/icons/topic-sense-ear.png"),
  "topic-sense-eye": require("../../../assets/icons/topic-sense-eye.png"),
  "topic-vitamins": require("../../../assets/icons/topic-vitamins.png"),
  "uptodate-logo": require("../../../assets/icons/uptodate-logo.png"),
} as const;

export type IconName = keyof typeof ICONS;

/** The icon registered under `name`, or null -- for icons looked up from
 * server data (lesson category/topic codes, calculator specialties) where a
 * new code might not have an icon drawn for it yet. */
export function iconFor(name: string): IconName | null {
  return name in ICONS ? (name as IconName) : null;
}

export function IconImage({
  name,
  size = 24,
  style,
}: {
  name: IconName;
  size?: number;
  style?: StyleProp<ImageStyle>;
}) {
  return (
    <Image
      source={ICONS[name]}
      style={[{ width: size, height: size, resizeMode: "contain" }, style]}
    />
  );
}
