# Generated by Django 5.1.15 on 2026-10-09 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculators', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculatorTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('name_fa', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='calculator',
            name='author',
        ),
        migrations.AddField(
            model_name='calculator',
            name='about_fa',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='calculator',
            name='description_fa',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='calculator',
            name='disclaimer_footer',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='calculator',
            name='disclaimer_footer_fa',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='calculator',
            name='error_checks',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='calculator',
            name='name_fa',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='calculator',
            name='uid',
            field=models.CharField(default='', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calculator',
            name='url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='calculator',
            name='calculator_id',
            field=models.CharField(max_length=20),
        ),
        migrations.RemoveField(
            model_name='calculator',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='calculator',
            name='tags',
        ),
        migrations.CreateModel(
            name='CalculatorCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('name_fa', models.CharField(blank=True, max_length=255)),
                ('is_main_category', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='calculators.calculatorcategory')),
            ],
            options={
                'verbose_name_plural': 'calculator categories',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='calculator',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='calculators', to='calculators.calculatorcategory'),
        ),
        migrations.AddField(
            model_name='calculator',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='calculators', to='calculators.calculatortag'),
        ),
    ]
