# Generated by Django 5.1.15 on 2026-10-09 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculators', '0002_calculatortag_remove_calculator_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculator',
            name='formula_strings_fa',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
