# Generated by Django 5.1.15 on 2026-07-16

from django.db import migrations, models


def sync_profile_names(apps, schema_editor):
    Profile = apps.get_model("accounts", "Profile")
    for profile in Profile.objects.select_related("user").iterator():
        profile.first_name = profile.user.first_name
        profile.last_name = profile.user.last_name
        profile.save(update_fields=["first_name", "last_name"])


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="first_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="profile",
            name="last_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.RunPython(sync_profile_names, migrations.RunPython.noop),
    ]
