# Generated by Django 5.1.15 on 2026-07-30 18:54

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


PERMISSIONS = {
    "view_raw_drug_data": "Can view raw drug data",
    "view_data_quality_center": "Can view the data quality center",
    "review_data_quality_suggestion": "Can review data quality suggestions",
    "approve_data_quality_suggestion": "Can approve data quality suggestions",
    "apply_data_quality_change": "Can apply data quality changes",
    "manage_drug_records": "Can manage drug records",
    "view_security_audit": "Can view security audit events",
    "manage_platform_roles": "Can manage platform roles",
}

ROLE_PERMISSIONS = {
    "learner": [],
    "verified_professional": [],
    "content_editor": [
        "view_data_quality_center",
        "review_data_quality_suggestion",
    ],
    "medical_reviewer": [
        "view_data_quality_center",
        "review_data_quality_suggestion",
    ],
    "data_quality_reviewer": [
        "view_data_quality_center",
        "review_data_quality_suggestion",
    ],
    "data_quality_approver": [
        "view_data_quality_center",
        "review_data_quality_suggestion",
        "approve_data_quality_suggestion",
    ],
    "support_agent": [],
    "billing_admin": [],
    "platform_admin": list(PERMISSIONS),
}


def prepare_identity_data(apps, schema_editor):
    User = apps.get_model("auth", "User")
    Token = apps.get_model("authtoken", "Token")
    ContentType = apps.get_model("contenttypes", "ContentType")
    Permission = apps.get_model("auth", "Permission")
    Role = apps.get_model("accounts", "Role")
    RoleAssignment = apps.get_model("accounts", "RoleAssignment")

    normalized_emails = {}
    for user in User.objects.order_by("id").iterator():
        email = (user.email or "").strip().lower()
        if email:
            duplicate_user_id = normalized_emails.get(email)
            if duplicate_user_id is not None:
                raise RuntimeError(
                    "Case-insensitive duplicate user emails must be resolved "
                    f"before applying accounts.0003: user {duplicate_user_id} "
                    f"and user {user.id} both use {email}."
                )
            normalized_emails[email] = user.id
        if user.email != email:
            user.email = email
            user.save(update_fields=["email"])

    Token.objects.all().delete()

    content_type, _ = ContentType.objects.get_or_create(
        app_label="accounts",
        model="securityauditevent",
    )
    permission_objects = {}
    for codename, name in PERMISSIONS.items():
        permission, _ = Permission.objects.update_or_create(
            content_type=content_type,
            codename=codename,
            defaults={"name": name},
        )
        permission_objects[codename] = permission

    roles = {}
    for key, codenames in ROLE_PERMISSIONS.items():
        role, _ = Role.objects.update_or_create(
            key=key,
            defaults={
                "name": key.replace("_", " ").title(),
                "description": f"System role: {key}.",
                "is_system": True,
            },
        )
        role.permissions.set(
            [permission_objects[codename] for codename in codenames]
        )
        roles[key] = role

    for user in User.objects.order_by("id").iterator():
        RoleAssignment.objects.get_or_create(
            user=user,
            role=roles["learner"],
            revoked_at__isnull=True,
        )
        if user.is_superuser:
            RoleAssignment.objects.get_or_create(
                user=user,
                role=roles["platform_admin"],
                revoked_at__isnull=True,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_names'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authtoken', '0004_alter_tokenproxy_options'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('is_system', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('permissions', models.ManyToManyField(blank=True, related_name='platform_roles', to='auth.permission')),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='RoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_assignments_created', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_assignments_revoked', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='accounts.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('access_token_hash', models.CharField(max_length=64, unique=True)),
                ('refresh_token_hash', models.CharField(max_length=64, unique=True)),
                ('access_expires_at', models.DateTimeField()),
                ('refresh_expires_at', models.DateTimeField()),
                ('last_used_at', models.DateTimeField()),
                ('step_up_verified_at', models.DateTimeField(blank=True, null=True)),
                ('refresh_rotated_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoke_reason', models.CharField(blank=True, max_length=120)),
                ('device_name', models.CharField(blank=True, max_length=120)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SessionRefreshToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('replaced_by_hash', models.CharField(blank=True, max_length=64)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresh_tokens', to='accounts.usersession')),
            ],
            options={
                'ordering': ['-issued_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SecurityAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=80)),
                ('request_id', models.CharField(blank=True, max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_actions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_audit_events', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='accounts.usersession')),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
                'permissions': [('view_raw_drug_data', 'Can view raw drug data'), ('view_data_quality_center', 'Can view the data quality center'), ('review_data_quality_suggestion', 'Can review data quality suggestions'), ('approve_data_quality_suggestion', 'Can approve data quality suggestions'), ('apply_data_quality_change', 'Can apply data quality changes'), ('manage_drug_records', 'Can manage drug records'), ('view_security_audit', 'Can view security audit events'), ('manage_platform_roles', 'Can manage platform roles')],
            },
        ),
        migrations.RunPython(
            prepare_identity_data,
            migrations.RunPython.noop,
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.RunSQL(
            sql=(
                "CREATE UNIQUE INDEX accounts_user_email_ci_uniq "
                "ON auth_user (LOWER(email)) WHERE email <> '';"
            ),
            reverse_sql="DROP INDEX IF EXISTS accounts_user_email_ci_uniq;",
        ),
        migrations.AddIndex(
            model_name='roleassignment',
            index=models.Index(fields=['user', 'revoked_at', 'expires_at'], name='accounts_role_user_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='roleassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('revoked_at__isnull', True)), fields=('user', 'role'), name='unique_active_user_role'),
        ),
        migrations.AddConstraint(
            model_name='roleassignment',
            constraint=models.CheckConstraint(condition=models.Q(('expires_at__isnull', True), ('expires_at__gt', models.F('created_at')), _connector='OR'), name='role_assignment_expiry_after_creation'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['user', 'revoked_at', 'refresh_expires_at'], name='acct_session_user_active_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['user', '-last_used_at'], name='acct_session_user_used_idx'),
        ),
        migrations.AddConstraint(
            model_name='usersession',
            constraint=models.CheckConstraint(condition=models.Q(('access_expires_at__gt', models.F('created_at'))), name='session_access_expiry_after_creation'),
        ),
        migrations.AddConstraint(
            model_name='usersession',
            constraint=models.CheckConstraint(condition=models.Q(('refresh_expires_at__gt', models.F('access_expires_at'))), name='session_refresh_expiry_after_access'),
        ),
        migrations.AddIndex(
            model_name='sessionrefreshtoken',
            index=models.Index(fields=['session', '-issued_at'], name='accounts_refresh_session_idx'),
        ),
        migrations.AddConstraint(
            model_name='sessionrefreshtoken',
            constraint=models.CheckConstraint(condition=models.Q(('expires_at__gt', models.F('issued_at'))), name='refresh_expiry_after_issue'),
        ),
        migrations.AddIndex(
            model_name='securityauditevent',
            index=models.Index(fields=['user', 'event_type', '-occurred_at'], name='accounts_audit_user_event_idx'),
        ),
        migrations.AddIndex(
            model_name='securityauditevent',
            index=models.Index(fields=['event_type', '-occurred_at'], name='accounts_audit_event_time_idx'),
        ),
    ]
