# Generated by Django 5.1.15 on 2026-09-08 22:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_phase2_identity_sessions_rbac'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=150)),
                ('study_field', models.CharField(blank=True, choices=[('pharmacy', 'Pharmacy'), ('medicine', 'Medicine'), ('nursing', 'Nursing')], max_length=20)),
                ('study_goal', models.CharField(blank=True, choices=[('residency', 'Residency exam'), ('final', 'Term finals'), ('clinical', 'Daily clinical review')], max_length=20)),
                ('study_level', models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('language', models.CharField(default='fa', max_length=5)),
                ('onboarded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learner_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
