# Generated by Django 5.1.15 on 2026-07-04 11:43

from django.db import migrations, models


def backfill_game_state(apps, schema_editor):
    GameSession = apps.get_model("games", "GameSession")
    GameAnswer = apps.get_model("games", "GameAnswer")

    GameSession.objects.filter(is_finished=True).update(status="finished")
    GameSession.objects.filter(is_finished=False).update(status="active")

    GameAnswer.objects.filter(remaining_seconds=0).update(time_expired=True)
    GameAnswer.objects.filter(score_delta__gt=0).update(xp_delta=10)


def reverse_game_state_backfill(apps, schema_editor):
    GameSession = apps.get_model("games", "GameSession")
    GameAnswer = apps.get_model("games", "GameAnswer")

    GameSession.objects.update(status="active", paused_at=None, total_paused_seconds=0)
    GameAnswer.objects.update(time_expired=False, xp_delta=0)


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_align_with_knowledge_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameanswer',
            name='scoring_rule_version',
            field=models.CharField(default='mvp-scoring-v1', max_length=80),
        ),
        migrations.AddField(
            model_name='gameanswer',
            name='time_expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gameanswer',
            name='xp_delta',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamequestion',
            name='paused_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('finished', 'Finished'), ('archived', 'Archived')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='total_paused_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gamequestion',
            name='question_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_game_state, reverse_game_state_backfill),
    ]
