# Generated by Django 5.1.15 on 2026-07-05 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_stabilize_assessment_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='target_category_key',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='mode',
            field=models.CharField(choices=[('random', 'Random'), ('category', 'Category'), ('all', 'All'), ('mistakes', 'Mistakes'), ('league', 'League')], max_length=20),
        ),
    ]
