# Generated by Django 5.1.15 on 2026-07-06 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_gamesession_target_category_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamequestion',
            name='timer_extended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamequestion',
            name='timer_extension_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamequestion',
            name='timer_extension_used',
            field=models.BooleanField(default=False),
        ),
    ]
