# Generated by Django 5.1.15 on 2026-07-15 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0007_relax_postgres_legacy_constraints"),
        ("learning", "0004_alter_learningobject_display_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QuizReminder",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("question_type", models.CharField(max_length=50)),
                ("prompt", models.TextField()),
                ("selected_answer", models.TextField(blank=True)),
                ("correct_answer", models.TextField()),
                ("explanation", models.TextField(blank=True)),
                ("options", models.JSONField(blank=True, default=list)),
                ("is_reviewed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "game_question",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reminders",
                        to="games.gamequestion",
                    ),
                ),
                (
                    "game_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reminders",
                        to="games.gamesession",
                    ),
                ),
                (
                    "knowledge_source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quiz_reminders",
                        to="learning.knowledgesource",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_reminders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["is_reviewed", "-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="quizreminder",
            constraint=models.UniqueConstraint(
                fields=("user", "game_question"),
                name="unique_user_game_question_reminder",
            ),
        ),
    ]
