# Generated by Django 5.1.15 on 2026-10-07 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0002_atccategory'),
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(choices=[('clinical_pharmacology', 'Mechanism'), ('indications_and_usage', 'Indication'), ('dosage_forms_and_strengths', 'Dosage forms'), ('boxed_warning', 'Boxed warning'), ('adverse_reactions', 'Adverse reactions'), ('warnings', 'Warnings'), ('pregnancy', 'Pregnancy')], max_length=40)),
                ('prompt_fa', models.TextField()),
                ('options_fa', models.JSONField(default=list)),
                ('correct_index', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_questions', to='drugs.ingredient')),
            ],
            options={
                'indexes': [models.Index(fields=['ingredient', 'field'], name='quiz_bankqu_ingredi_464cdd_idx')],
            },
        ),
    ]
