# Generated by Django 5.1.15 on 2026-10-07 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_bankquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsession',
            name='atc_code',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='quizsession',
            name='category',
            field=models.CharField(max_length=32),
        ),
    ]
