# Generated by Django 5.1.15 on 2026-10-07 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_quizsession_atc_code_alter_quizsession_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='bank_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='quiz.bankquestion'),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='field',
            field=models.CharField(blank=True, choices=[('clinical_pharmacology', 'Mechanism'), ('indications_and_usage', 'Indication'), ('dosage_forms_and_strengths', 'Dosage forms'), ('boxed_warning', 'Boxed warning'), ('adverse_reactions', 'Adverse reactions'), ('warnings', 'Warnings'), ('pregnancy', 'Pregnancy')], max_length=40),
        ),
    ]
