# Generated by Django 5.1.15 on 2026-10-07 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_quizquestion_bank_question_quizquestion_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankquestion',
            name='difficulty',
            field=models.CharField(choices=[('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='bankquestion',
            name='field',
            field=models.CharField(choices=[('indications_and_usage', 'Indication'), ('adverse_reactions', 'Adverse reactions'), ('warnings', 'Warnings'), ('contraindications', 'Absolute contraindication'), ('dosage_and_administration', 'Dosing')], max_length=40),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='field',
            field=models.CharField(blank=True, choices=[('indications_and_usage', 'Indication'), ('adverse_reactions', 'Adverse reactions'), ('warnings', 'Warnings'), ('contraindications', 'Absolute contraindication'), ('dosage_and_administration', 'Dosing')], max_length=40),
        ),
    ]
