# Generated by Django 5.1.15 on 2026-09-09 00:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drugs', '0002_atccategory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionEdit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editor_username', models.CharField(blank=True, max_length=150)),
                ('ingredient_name', models.CharField(max_length=255)),
                ('field', models.CharField(max_length=40)),
                ('before_fa', models.TextField(blank=True)),
                ('after_fa', models.TextField(blank=True)),
                ('before_en', models.TextField(blank=True)),
                ('after_en', models.TextField(blank=True)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('editor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_edits', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edits', to='drugs.ingredientprofilesection')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='dqc_edit_recent_idx')],
            },
        ),
    ]
