# Generated by Django 5.1.15 on 2026-10-07 23:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_quality_center', '0001_initial'),
        ('drugs', '0002_atccategory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionedit',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_edit_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sectionedit',
            name='approved_by_username',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.CreateModel(
            name='SectionEditRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_by_username', models.CharField(blank=True, max_length=150)),
                ('ingredient_name', models.CharField(max_length=255)),
                ('field', models.CharField(max_length=40)),
                ('before_fa', models.TextField(blank=True)),
                ('after_fa', models.TextField(blank=True)),
                ('before_en', models.TextField(blank=True)),
                ('after_en', models.TextField(blank=True)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('reviewed_by_username', models.CharField(blank=True, max_length=150)),
                ('review_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_edit_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_edit_reviews', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_requests', to='drugs.ingredientprofilesection')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='dqc_request_status_idx'), models.Index(fields=['section', 'status'], name='dqc_request_section_idx')],
            },
        ),
    ]
