# Generated by Django 5.1.15 on 2026-10-07 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_quality_center', '0002_sectionedit_approved_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionedit',
            name='field',
            field=models.CharField(choices=[('indications_and_usage', 'Indications and usage'), ('dosage_and_administration', 'Dosage and administration'), ('dosage_forms_and_strengths', 'Dosage forms and strengths'), ('contraindications', 'Contraindications'), ('do_not_use', 'Do not use'), ('boxed_warning', 'Boxed warning'), ('warnings', 'Warnings'), ('adverse_reactions', 'Adverse reactions'), ('drug_interactions', 'Drug interactions'), ('pregnancy', 'Pregnancy'), ('abuse', 'Abuse'), ('clinical_pharmacology', 'Clinical pharmacology')], max_length=40),
        ),
        migrations.AlterField(
            model_name='sectioneditrequest',
            name='field',
            field=models.CharField(choices=[('indications_and_usage', 'Indications and usage'), ('dosage_and_administration', 'Dosage and administration'), ('dosage_forms_and_strengths', 'Dosage forms and strengths'), ('contraindications', 'Contraindications'), ('do_not_use', 'Do not use'), ('boxed_warning', 'Boxed warning'), ('warnings', 'Warnings'), ('adverse_reactions', 'Adverse reactions'), ('drug_interactions', 'Drug interactions'), ('pregnancy', 'Pregnancy'), ('abuse', 'Abuse'), ('clinical_pharmacology', 'Clinical pharmacology')], max_length=40),
        ),
    ]
