# Generated by Django 5.1.15 on 2026-09-08 23:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atc_code', models.CharField(max_length=3)),
                ('read_drug_slugs', models.JSONField(blank=True, default=list)),
                ('scroll_pct', models.PositiveSmallIntegerField(default=0)),
                ('last_opened_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_opened_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'atc_code'), name='lessons_unique_user_chapter')],
            },
        ),
    ]
