# Generated by Django 5.1.15 on 2026-09-11 11:20, hand-edited to preserve data:
# reordered so the ReadDrug table exists and is backfilled from
# ChapterProgress.read_drug_slugs *before* that column is dropped.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def copy_read_drug_slugs_to_readdrug(apps, schema_editor):
    ChapterProgress = apps.get_model("lessons", "ChapterProgress")
    ReadDrug = apps.get_model("lessons", "ReadDrug")

    to_create = {}
    for user_id, slug in (
        ChapterProgress.objects.exclude(read_drug_slugs=[])
        .values_list("user_id", "read_drug_slugs")
    ):
        for ingredient_slug in slug:
            to_create[(user_id, ingredient_slug)] = ReadDrug(
                user_id=user_id, ingredient_slug=ingredient_slug
            )
    ReadDrug.objects.bulk_create(to_create.values(), ignore_conflicts=True)


def noop_reverse(apps, schema_editor):
    """Not reversible: which chapter a globally-read drug came from is lost.
    A reverse migrate would have to drop ReadDrug's data anyway (the field
    it repopulates no longer exists at that point), so there's nothing
    meaningful to restore."""


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadDrug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_slug', models.CharField(max_length=255)),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_drugs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'ingredient_slug'), name='lessons_unique_user_read_drug')],
            },
        ),
        migrations.RunPython(copy_read_drug_slugs_to_readdrug, noop_reverse),
        migrations.RemoveField(
            model_name='chapterprogress',
            name='read_drug_slugs',
        ),
    ]
