# Generated by Django 5.1.15 on 2026-07-06 08:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIDataBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('batch_type', models.CharField(choices=[('health_check', 'Health check'), ('suggestion_generation', 'Suggestion generation'), ('apply', 'Apply'), ('report', 'Report')], max_length=40)),
                ('status', models.CharField(choices=[('created', 'Created'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='created', max_length=40)),
                ('source_database', models.CharField(blank=True, max_length=500)),
                ('target_scope', models.JSONField(blank=True, default=dict)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('created_by', models.CharField(blank=True, max_length=150)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ai_data_batches',
                'indexes': [models.Index(fields=['batch_type', 'status'], name='ai_data_bat_batch_t_1da5cd_idx'), models.Index(fields=['created_at'], name='ai_data_bat_created_ba32f2_idx')],
            },
        ),
        migrations.CreateModel(
            name='AIDataSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=160)),
                ('record_id', models.CharField(max_length=80)),
                ('field_name', models.CharField(max_length=160)),
                ('old_value', models.TextField(blank=True)),
                ('suggested_value', models.TextField(blank=True)),
                ('suggestion_type', models.CharField(max_length=80)),
                ('reason', models.TextField(blank=True)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('risk_level', models.CharField(choices=[('safe', 'Safe'), ('needs_review', 'Needs review'), ('risky', 'Risky')], default='needs_review', max_length=40)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('edited', 'Edited'), ('applied', 'Applied'), ('failed', 'Failed')], default='pending', max_length=40)),
                ('provider', models.CharField(default='local-mock', max_length=80)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.CharField(blank=True, max_length=150)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='ai_data_pipeline.aidatabatch')),
            ],
            options={
                'db_table': 'ai_data_suggestions',
            },
        ),
        migrations.CreateModel(
            name='AIDataChangeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=160)),
                ('record_id', models.CharField(max_length=80)),
                ('field_name', models.CharField(max_length=160)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('reason', models.TextField(blank=True)),
                ('suggestion_type', models.CharField(blank=True, max_length=80)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('risk_level', models.CharField(blank=True, max_length=40)),
                ('applied_by', models.CharField(blank=True, max_length=150)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('rollback_batch_id', models.CharField(blank=True, max_length=80)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_history', to='ai_data_pipeline.aidatabatch')),
                ('suggestion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_history', to='ai_data_pipeline.aidatasuggestion')),
            ],
            options={
                'db_table': 'ai_data_change_history',
            },
        ),
        migrations.CreateModel(
            name='AIDataTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=160)),
                ('record_id', models.CharField(max_length=80)),
                ('source_field', models.CharField(max_length=160)),
                ('source_value', models.TextField(blank=True)),
                ('language_code', models.CharField(default='en', max_length=20)),
                ('translated_value', models.TextField(blank=True)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translations', to='ai_data_pipeline.aidatabatch')),
                ('suggestion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translations', to='ai_data_pipeline.aidatasuggestion')),
            ],
            options={
                'db_table': 'ai_data_translations',
            },
        ),
        migrations.CreateModel(
            name='AIDataReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(max_length=80)),
                ('format', models.CharField(default='json', max_length=20)),
                ('path', models.CharField(blank=True, max_length=500)),
                ('content', models.JSONField(blank=True, default=dict)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='ai_data_pipeline.aidatabatch')),
            ],
            options={
                'db_table': 'ai_data_reports',
                'indexes': [models.Index(fields=['batch', 'report_type'], name='ai_data_rep_batch_i_48a774_idx'), models.Index(fields=['created_at'], name='ai_data_rep_created_6b7abe_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='aidatasuggestion',
            index=models.Index(fields=['batch', 'status'], name='ai_data_sug_batch_i_de36c1_idx'),
        ),
        migrations.AddIndex(
            model_name='aidatasuggestion',
            index=models.Index(fields=['table_name', 'record_id'], name='ai_data_sug_table_n_b551ad_idx'),
        ),
        migrations.AddIndex(
            model_name='aidatasuggestion',
            index=models.Index(fields=['suggestion_type', 'risk_level'], name='ai_data_sug_suggest_a326e1_idx'),
        ),
        migrations.AddIndex(
            model_name='aidatachangehistory',
            index=models.Index(fields=['batch', 'applied_at'], name='ai_data_cha_batch_i_a60897_idx'),
        ),
        migrations.AddIndex(
            model_name='aidatachangehistory',
            index=models.Index(fields=['table_name', 'record_id'], name='ai_data_cha_table_n_db59ee_idx'),
        ),
        migrations.AddIndex(
            model_name='aidatatranslation',
            index=models.Index(fields=['table_name', 'record_id'], name='ai_data_tra_table_n_5423f7_idx'),
        ),
        migrations.AddIndex(
            model_name='aidatatranslation',
            index=models.Index(fields=['language_code'], name='ai_data_tra_languag_68973f_idx'),
        ),
        migrations.AddConstraint(
            model_name='aidatatranslation',
            constraint=models.UniqueConstraint(fields=('table_name', 'record_id', 'source_field', 'language_code'), name='unique_ai_translation_target'),
        ),
    ]
