# Generated by Django 5.1.15 on 2026-07-06 09:28

import django.db.models.deletion
from django.db import migrations, models


def normalize_provider_names(apps, schema_editor):
    suggestion = apps.get_model('ai_data_pipeline', 'AIDataSuggestion')
    suggestion.objects.filter(provider='local-rules').update(provider='rules')
    suggestion.objects.filter(provider='local-mock').update(provider='mock')


class Migration(migrations.Migration):

    dependencies = [
        ('ai_data_pipeline', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aidatasuggestion',
            name='provider',
            field=models.CharField(default='rules', max_length=80),
        ),
        migrations.RunPython(normalize_provider_names, migrations.RunPython.noop),
        migrations.CreateModel(
            name='AIDataJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('health_check', 'Health check'), ('normalization', 'Normalization'), ('terminology_check', 'Terminology check'), ('duplicate_detection', 'Duplicate detection'), ('medical_validation', 'Medical validation'), ('translation', 'Translation'), ('full_rules_review', 'Full rules review')], max_length=80)),
                ('provider', models.CharField(default='rules', max_length=80)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=40)),
                ('parameters_json', models.JSONField(blank=True, default=dict)),
                ('total_records', models.PositiveIntegerField(default=0)),
                ('processed_records', models.PositiveIntegerField(default=0)),
                ('suggestions_created', models.PositiveIntegerField(default=0)),
                ('errors_count', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=150)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='ai_data_pipeline.aidatabatch')),
            ],
            options={
                'db_table': 'ai_data_jobs',
                'indexes': [models.Index(fields=['batch', 'status'], name='ai_data_job_batch_i_e82b3a_idx'), models.Index(fields=['job_type', 'provider'], name='ai_data_job_job_typ_c355ad_idx'), models.Index(fields=['created_at'], name='ai_data_job_created_1c1588_idx')],
            },
        ),
    ]
